In [2787]:
import numpy as np
import matplotlib.pyplot as plt

# pip install pandas

In [2788]:
import pandas as pd

# sursa dataset: https://www.kaggle.com/code/prasadperera/the-boston-housing-dataset

In [2789]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df = pd.read_csv("datasets/Boston_data.csv", names = column_names, header=None, delimiter=r"\s+")
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [2790]:
df = pd.read_csv("datasets/Boston_cu_headere.csv", index_col=0)
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [2791]:
df.dtypes

crim       float64
zn         float64
indus      float64
chas         int64
nox        float64
rm         float64
age        float64
dis        float64
rad          int64
tax          int64
ptratio    float64
black      float64
lstat      float64
medv       float64
dtype: object

In [2792]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [2793]:
type(df)

pandas.core.frame.DataFrame

In [2794]:
df.keys()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [2795]:
medv = df["medv"]
type(medv)

pandas.core.series.Series

In [2796]:
medv = df[ [ "medv"] ]
type(medv)

pandas.core.frame.DataFrame

In [2797]:
# pentru a lua o coloana doar cu 1 singur set de paranteze drepte -> Serie
df[  "medv" ]

1      24.0
2      21.6
3      34.7
4      33.4
5      36.2
       ...
502    22.4
503    20.6
504    23.9
505    22.0
506    11.9
Name: medv, Length: 506, dtype: float64

In [2798]:
# pentru a lua o coloana cu 2 seturi de paranteze drepte -> DataFrame
y = df[ [ "medv"] ]
y

     medv
1    24.0
2    21.6
3    34.7
4    33.4
5    36.2
..    ...
502  22.4
503  20.6
504  23.9
505  22.0
506  11.9

[506 rows x 1 columns]

In [2799]:
df.keys()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [2800]:
x = df[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat']]
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [2801]:
x = df.drop("medv", axis=1) # axis=0 orizontala si axis=1 este pe verticala
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [2802]:
from sklearn.linear_model import LinearRegression

In [2803]:
model = LinearRegression()
model

LinearRegression()

In [2804]:
from sklearn.model_selection import train_test_split

In [2805]:
x_train, x_test, y_train, y_test = train_test_split(x, y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((379, 13), (127, 13), (379, 1), (127, 1))

In [2806]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)#, random_state=142)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404, 1), (102, 1))

In [2807]:
model.fit(x_train, y_train)

LinearRegression()

In [2808]:
y_prezis = model.predict(x_train)
y_prezis

array([[30.63557783],
       [23.61465443],
       [17.5206977 ],
       [22.61755634],
       [32.91150104],
       [23.26104039],
       [34.15156835],
       [ 2.31380495],
       [27.46575388],
       [21.23897432],
       [15.42027511],
       [13.49061833],
       [13.18802779],
       [10.81059139],
       [32.60205226],
       [34.06926004],
       [24.73566481],
       [37.72438144],
       [15.70137133],
       [34.78861501],
       [19.26553398],
       [19.93551643],
       [27.00839677],
       [30.62741464],
       [13.75958704],
       [30.86264521],
       [23.17774722],
       [21.52344836],
       [24.95187786],
       [28.77414057],
       [30.55451781],
       [20.26926385],
       [25.42343769],
       [18.49489466],
       [12.04063218],
       [19.22139457],
       [40.37981068],
       [36.15801147],
       [17.37133754],
       [19.94279145],
       [22.32011469],
       [16.7934027 ],
       [29.78944316],
       [21.33939791],
       [22.36790647],
       [29.71805065],
       [34.74216652],
       [ 2.81047071],
       [22.82791314],
       [15.90132364],
       [16.89060214],
       [42.56639968],
       [24.7321047 ],
       [25.52005202],
       [23.66656593],
       [20.42304673],
       [12.46158114],
       [18.1136581 ],
       [20.68561483],
       [31.44160648],
       [28.48830497],
       [22.6017185 ],
       [14.23858909],
       [19.53731295],
       [20.39628379],
       [19.93023523],
       [33.21658095],
       [38.35804629],
       [25.13598489],
       [32.95071199],
       [19.46989984],
       [24.64560843],
       [42.60349225],
       [18.09630016],
       [16.51958604],
       [22.38793218],
       [30.64158887],
       [21.08786121],
       [11.24548094],
       [27.45060536],
       [32.02586286],
       [25.07909772],
       [35.91342388],
       [25.13075019],
       [ 7.36669561],
       [35.44524632],
       [11.27602238],
       [21.11889423],
       [31.16696144],
       [18.34959138],
       [24.4933754 ],
       [33.53346756],
       [20.93520118],
       [24.54085513],
       [13.80233108],
       [22.58546401],
       [20.196537  ],
       [21.82798213],
       [33.95463127],
       [16.64066155],
       [23.01345073],
       [31.0175057 ],
       [36.67887855],
       [17.24336292],
       [23.70809547],
       [26.51221416],
       [29.16392689],
       [19.26684243],
       [21.22406667],
       [23.92169585],
       [23.27490706],
       [32.9460861 ],
       [14.5296447 ],
       [15.93849416],
       [33.81376823],
       [26.23994683],
       [17.79470986],
       [35.33401761],
       [33.18306096],
       [29.32232375],
       [20.58902361],
       [20.67122556],
       [37.14092198],
       [10.28021975],
       [24.0232086 ],
       [30.60385201],
       [16.02605861],
       [14.85486727],
       [24.02294776],
       [23.11793705],
       [17.87625492],
       [18.94118492],
       [20.48338395],
       [16.49498581],
       [14.46630076],
       [25.06995507],
       [20.27683623],
       [24.04837511],
       [19.31571159],
       [13.36516945],
       [22.25970771],
       [37.06789584],
       [21.80693901],
       [18.58280167],
       [28.85192165],
       [15.57089163],
       [21.67322244],
       [19.65518257],
       [27.99096067],
       [38.77579297],
       [ 8.16310679],
       [21.6871134 ],
       [26.06615765],
       [19.47794236],
       [31.62660598],
       [21.4263394 ],
       [32.65124468],
       [27.27565421],
       [35.52353414],
       [23.55154395],
       [ 8.8601056 ],
       [18.16509247],
       [13.67570788],
       [24.29644971],
       [18.95061435],
       [24.84941298],
       [27.10932518],
       [22.22499762],
       [23.34096458],
       [27.11527755],
       [18.31750857],
       [34.33897447],
       [33.97741612],
       [25.62524518],
       [28.51342366],
       [21.22851811],
       [23.10361499],
       [18.61471863],
       [32.80724363],
       [15.5335772 ],
       [11.39221675],
       [33.74279515],
       [29.14870943],
       [22.16332932],
       [25.51024732],
       [19.7901127 ],
       [19.42398562],
       [26.28082479],
       [25.47340301],
       [27.1153503 ],
       [35.30493663],
       [25.14097791],
       [25.03864016],
       [24.21075224],
       [28.95039718],
       [12.28530729],
       [14.27715493],
       [17.36892711],
       [ 8.9856152 ],
       [22.77740909],
       [13.31965983],
       [28.93068968],
       [13.69851844],
       [ 9.74319731],
       [25.24666893],
       [39.69118403],
       [ 7.68688823],
       [32.88954281],
       [24.63595563],
       [16.60059113],
       [12.86544685],
       [14.82830572],
       [10.43458996],
       [20.83090534],
       [25.81003371],
       [28.59542761],
       [21.34049142],
       [21.84242421],
       [37.9498925 ],
       [19.47485805],
       [13.36114963],
       [23.17414201],
       [25.648233  ],
       [12.87342048],
       [19.00089302],
       [30.66564385],
       [30.43533774],
       [12.79381924],
       [31.40908805],
       [13.9768245 ],
       [23.05933954],
       [ 1.72248509],
       [ 6.548966  ],
       [28.43394936],
       [15.70332713],
       [19.69375094],
       [25.22923965],
       [-3.18707802],
       [33.1133203 ],
       [18.737886  ],
       [25.26054645],
       [26.92507228],
       [24.14845924],
       [20.70520666],
       [25.05551131],
       [18.31229879],
       [23.05060682],
       [14.82543744],
       [32.06057515],
       [17.96039727],
       [41.43386326],
       [34.09548439],
       [ 7.72544688],
       [29.70894893],
       [23.07147336],
       [21.09376494],
       [21.79566428],
       [14.57111968],
       [27.41187146],
       [28.727873  ],
       [22.45753336],
       [30.11674569],
       [15.00620176],
       [26.39361442],
       [20.64958465],
       [33.47498481],
       [36.10951379],
       [27.37664624],
       [13.22826232],
       [16.54113326],
       [24.80240137],
       [25.29364325],
       [17.07657938],
       [36.96394159],
       [26.65960448],
       [20.23441463],
       [22.19794086],
       [19.74677217],
       [31.53219472],
       [21.76907677],
       [20.41538131],
       [23.34734741],
       [41.67053067],
       [35.58640219],
       [19.09709646],
       [21.2008563 ],
       [13.38919102],
       [28.45181569],
       [40.48059532],
       [16.93931948],
       [17.95504799],
       [15.1865358 ],
       [11.24146835],
       [20.49137112],
       [15.13574804],
       [27.17655753],
       [22.41988829],
       [32.17193807],
       [25.51323657],
       [28.21092846],
       [ 6.80666521],
       [21.31191822],
       [14.06910528],
       [25.25991927],
       [20.71385553],
       [21.70652942],
       [29.45859498],
       [33.09576494],
       [25.92824895],
       [28.07176457],
       [19.65094813],
       [14.72122181],
       [23.03774428],
       [ 8.02073904],
       [24.73032861],
       [23.04171788],
       [28.38155809],
       [18.65780607],
       [33.97029018],
       [14.41376704],
       [40.21152884],
       [22.13637528],
       [17.72640044],
       [20.34353696],
       [21.14752069],
       [27.80867879],
       [ 7.28566425],
       [25.93608558],
       [26.0183861 ],
       [24.68078107],
       [24.61536866],
       [39.00149766],
       [22.84316765],
       [16.81923846],
       [27.87068089],
       [24.07909332],
       [20.79874038],
       [20.43388998],
       [21.44541687],
       [30.19269182],
       [20.46168926],
       [ 4.21476747],
       [26.11709946],
       [17.72840824],
       [ 8.68379511],
       [18.56189639],
       [18.1399952 ],
       [34.39460834],
       [27.93915082],
       [24.15659301],
       [20.27888877],
       [16.89550464],
       [20.2911185 ],
       [28.51180389],
       [24.21040925],
       [18.92968652],
       [23.69523154],
       [20.52825013],
       [13.32719875],
       [35.55424996],
       [34.52292817],
       [20.57755395],
       [ 8.94357721],
       [23.50612478],
       [25.50149924],
       [21.13693834],
       [13.16797889],
       [28.95231655],
       [14.24952661],
       [27.24255306],
       [19.55084   ],
       [15.44270009],
       [23.73989842],
       [38.08991412],
       [30.82171797],
       [30.88904202],
       [22.89356254],
       [20.35010195],
       [18.38420926],
       [23.95728078],
       [19.33802666],
       [17.18321285],
       [13.20365572],
       [17.05593332],
       [22.65123713],
       [25.51954758],
       [32.46885326],
       [26.80121162],
       [14.23482365],
       [19.60188973],
       [16.02287617],
       [31.57168171],
       [17.86103043],
       [19.77782471],
       [17.48675759],
       [18.84030387],
       [24.2193397 ],
       [19.87389589],
       [23.82073281],
       [29.97096805],
       [30.09395567],
       [10.3947632 ],
       [24.56602875],
       [17.78669117]])

In [2809]:
real_vs_prezis_df = pd.DataFrame({"y_real":y_train["medv"], "y_prezis":y_prezis.flatten()})
real_vs_prezis_df

     y_real   y_prezis
267    30.7  30.635578
209    24.4  23.614654
69     17.4  17.520698
211    21.7  22.617556
161    27.0  32.911501
..      ...        ...
342    32.7  29.970968
192    30.5  30.093956
406     5.0  10.394763
57     24.7  24.566029
450    13.0  17.786691

[404 rows x 2 columns]

In [2810]:
real_vs_prezis_df["score"] = real_vs_prezis_df["y_real"] - real_vs_prezis_df["y_prezis"]
real_vs_prezis_df

     y_real   y_prezis     score
267    30.7  30.635578  0.064422
209    24.4  23.614654  0.785346
69     17.4  17.520698 -0.120698
211    21.7  22.617556 -0.917556
161    27.0  32.911501 -5.911501
..      ...        ...       ...
342    32.7  29.970968  2.729032
192    30.5  30.093956  0.406044
406     5.0  10.394763 -5.394763
57     24.7  24.566029  0.133971
450    13.0  17.786691 -4.786691

[404 rows x 3 columns]

In [2811]:
real_vs_prezis_df["score"] = (real_vs_prezis_df["y_real"] - real_vs_prezis_df["y_prezis"]) ** 2
real_vs_prezis_df

     y_real   y_prezis      score
267    30.7  30.635578   0.004150
209    24.4  23.614654   0.616768
69     17.4  17.520698   0.014568
211    21.7  22.617556   0.841910
161    27.0  32.911501  34.945845
..      ...        ...        ...
342    32.7  29.970968   7.447615
192    30.5  30.093956   0.164872
406     5.0  10.394763  29.103470
57     24.7  24.566029   0.017948
450    13.0  17.786691  22.912412

[404 rows x 3 columns]

In [2812]:
real_vs_prezis_df["score"] = np.sqrt((real_vs_prezis_df["y_real"] - real_vs_prezis_df["y_prezis"]) ** 2)
real_vs_prezis_df

     y_real   y_prezis     score
267    30.7  30.635578  0.064422
209    24.4  23.614654  0.785346
69     17.4  17.520698  0.120698
211    21.7  22.617556  0.917556
161    27.0  32.911501  5.911501
..      ...        ...       ...
342    32.7  29.970968  2.729032
192    30.5  30.093956  0.406044
406     5.0  10.394763  5.394763
57     24.7  24.566029  0.133971
450    13.0  17.786691  4.786691

[404 rows x 3 columns]

In [2813]:
real_vs_prezis_df["score"].sum()

np.float64(1371.3372928610129)

In [2814]:
real_vs_prezis_df["score"].sum() / real_vs_prezis_df["score"].count()

np.float64(3.3943992397549825)

In [2815]:
real_vs_prezis_df["score"].mean()

np.float64(3.3943992397549825)

In [2816]:
real_vs_prezis_df["score"].mean() / 2

np.float64(1.6971996198774912)

In [2817]:
from sklearn.metrics import r2_score

In [2818]:
y_prezis = model.predict(x_train)
r2_score(y_train, y_prezis)

0.7184285410428757

In [2819]:
model.score(x_train, y_train)

0.7184285410428757

In [2820]:
x.iloc[100]

crim         0.14866
zn           0.00000
indus        8.56000
chas         0.00000
nox          0.52000
rm           6.72700
age         79.90000
dis          2.77780
rad          5.00000
tax        384.00000
ptratio     20.90000
black      394.76000
lstat        9.42000
Name: 101, dtype: float64

In [2821]:
model.predict([x.iloc[100]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[24.4933754]])

# Antrenarea unui alt model de regresie liniara

In [2822]:
from sklearn.neighbors import KNeighborsRegressor

In [2823]:
knn_model = KNeighborsRegressor(n_neighbors=3)
knn_model

KNeighborsRegressor(n_neighbors=3)

In [2824]:
knn_model.fit(x_train, y_train)

KNeighborsRegressor(n_neighbors=3)

In [2825]:
model

LinearRegression()

In [2826]:
knn_model.score(x_train, y_train)

0.7735887436805016

In [2827]:
model.score(x_train, y_train)

0.7184285410428757

In [2828]:
knn_scores = {}


for k in range(2, 11):
    inner_knn_model = KNeighborsRegressor(n_neighbors=k)
    inner_knn_model.fit(x_train, y_train)
    score_result =  inner_knn_model.score(x_train, y_train)
    knn_scores[k] = score_result

In [2829]:
knn_scores

{2: 0.8181125594753362,
 3: 0.7735887436805016,
 4: 0.7285566096927669,
 5: 0.676839924703627,
 6: 0.6608058020686294,
 7: 0.6258894182998389,
 8: 0.5918199370862103,
 9: 0.5800937585806873,
 10: 0.5521585507365508}

In [2830]:
score_values = np.array(list(knn_scores.values()))
score_values.max(), score_values.argmax()

(np.float64(0.8181125594753362), np.int64(0))

In [2831]:
from sklearn.model_selection import GridSearchCV

In [2832]:
estimator_model = KNeighborsRegressor()
estimator_model

KNeighborsRegressor()

In [2833]:
parameter_grid = {'n_neighbors' : range(2, 11)}

In [2834]:
grid_model = GridSearchCV(estimator_model, parameter_grid)
grid_model

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': range(2, 11)})

In [2835]:
grid_model.fit(x_train, y_train)
grid_model

GridSearchCV(estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': range(2, 11)})

In [2836]:
grid_model.score(x_test, y_test)

0.556440288333327

In [2837]:
grid_model.best_estimator_

KNeighborsRegressor(n_neighbors=3)

In [2838]:
grid_model.best_estimator_.n_neighbors

3

In [2839]:
grid_model.best_estimator_.score(x_test, y_test)

0.556440288333327