In [941]:
import numpy as np
import matplotlib.pyplot as plt

# pip install pandas

In [942]:
import pandas as pd

# sursa dataset: https://www.kaggle.com/code/prasadperera/the-boston-housing-dataset

In [943]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
df = pd.read_csv("datasets/Boston_data.csv", names = column_names, header=None, delimiter=r"\s+")
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [944]:
df = pd.read_csv("datasets/Boston_cu_headere.csv", index_col=0)
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [945]:
df.dtypes

crim       float64
zn         float64
indus      float64
chas         int64
nox        float64
rm         float64
age        float64
dis        float64
rad          int64
tax          int64
ptratio    float64
black      float64
lstat      float64
medv       float64
dtype: object

In [946]:
df.describe()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [947]:
type(df)

pandas.core.frame.DataFrame

In [948]:
df.keys()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [949]:
medv = df["medv"]
type(medv)

pandas.core.series.Series

In [950]:
medv = df[ [ "medv"] ]
type(medv)

pandas.core.frame.DataFrame

In [951]:
# pentru a lua o coloana doar cu 1 singur set de paranteze drepte -> Serie
df[  "medv" ]

1      24.0
2      21.6
3      34.7
4      33.4
5      36.2
       ...
502    22.4
503    20.6
504    23.9
505    22.0
506    11.9
Name: medv, Length: 506, dtype: float64

In [952]:
# pentru a lua o coloana cu 2 seturi de paranteze drepte -> DataFrame
y = df[ [ "medv"] ]
y

     medv
1    24.0
2    21.6
3    34.7
4    33.4
5    36.2
..    ...
502  22.4
503  20.6
504  23.9
505  22.0
506  11.9

[506 rows x 1 columns]

In [953]:
df.keys()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [954]:
x = df[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'black', 'lstat']]
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [955]:
x = df.drop("medv", axis=1) # axis=0 orizontala si axis=1 este pe verticala
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [956]:
from sklearn.linear_model import LinearRegression

In [957]:
model = LinearRegression()
model

LinearRegression()

In [958]:
from sklearn.model_selection import train_test_split

In [959]:
x_train, x_test, y_train, y_test = train_test_split(x, y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((379, 13), (127, 13), (379, 1), (127, 1))

In [960]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=101)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404, 1), (102, 1))

In [961]:
model.fit(x_train, y_train)

LinearRegression()

In [962]:
y_prezis = model.predict(x_train)
y_prezis

array([[26.53118268],
       [24.34582914],
       [22.65581007],
       [25.1791558 ],
       [24.75060315],
       [30.67268181],
       [38.43015707],
       [32.37769561],
       [22.93458281],
       [37.27031248],
       [24.30291082],
       [21.92938733],
       [30.1444144 ],
       [27.14883374],
       [28.56248023],
       [31.091853  ],
       [26.22772107],
       [28.61026855],
       [16.9982506 ],
       [20.18297686],
       [21.06925227],
       [36.12065533],
       [24.43912021],
       [23.26612938],
       [14.70337302],
       [ 5.82627158],
       [13.8820259 ],
       [23.49244065],
       [26.74984399],
       [34.24726964],
       [23.35514739],
       [20.48312693],
       [25.66346485],
       [25.26606488],
       [30.10631932],
       [26.7559211 ],
       [35.51528447],
       [22.65113314],
       [13.64085042],
       [36.83629749],
       [32.68887266],
       [15.82919424],
       [24.92826264],
       [19.26186021],
       [19.54319254],
       [24.97821384],
       [25.41302508],
       [29.84405356],
       [16.72117032],
       [17.1660538 ],
       [42.6388382 ],
       [35.24151354],
       [22.17180431],
       [21.66389873],
       [22.99196171],
       [13.11981583],
       [22.72646391],
       [25.03134014],
       [19.59500255],
       [28.65010209],
       [43.36757126],
       [22.28923729],
       [26.29797764],
       [21.99017724],
       [18.24949383],
       [31.19412342],
       [18.18828326],
       [12.26244838],
       [19.37313246],
       [33.81740552],
       [36.93817579],
       [20.61409058],
       [ 1.13324651],
       [18.2027634 ],
       [27.90928892],
       [18.79462894],
       [28.13801125],
       [24.67142919],
       [26.40322027],
       [20.42571442],
       [22.3938151 ],
       [40.66357309],
       [26.46331704],
       [39.10309816],
       [24.55189144],
       [15.7411428 ],
       [21.54883192],
       [17.45032917],
       [25.04331434],
       [34.88767637],
       [ 9.37049412],
       [20.40467162],
       [19.88982124],
       [26.85609275],
       [25.56863566],
       [18.33801196],
       [20.99002588],
       [32.97722737],
       [19.94752132],
       [22.8988579 ],
       [28.11440253],
       [27.23635478],
       [18.76818751],
       [17.36246562],
       [16.53274892],
       [17.21798924],
       [28.47623473],
       [19.75236182],
       [18.09470864],
       [13.38887251],
       [32.16036445],
       [17.62691212],
       [22.25884592],
       [20.12380887],
       [35.15059429],
       [17.9376243 ],
       [33.20565116],
       [16.47512084],
       [10.51864985],
       [-4.56702331],
       [20.89515084],
       [ 9.6840749 ],
       [27.56325317],
       [28.83242478],
       [22.1473421 ],
       [27.0202133 ],
       [23.95385816],
       [17.30960896],
       [13.9404561 ],
       [27.07287509],
       [25.41996553],
       [ 8.39585823],
       [23.36468715],
       [26.37049289],
       [ 9.37923092],
       [15.56208075],
       [26.84984633],
       [23.62543081],
       [34.72770821],
       [23.8371756 ],
       [18.91123176],
       [12.06610955],
       [20.50712609],
       [20.27654702],
       [15.14463049],
       [25.37113279],
       [41.18903964],
       [19.84867545],
       [17.37456334],
       [ 9.04954139],
       [24.65817905],
       [32.06331701],
       [17.76885175],
       [34.6062947 ],
       [23.00843851],
       [19.45520174],
       [34.46651193],
       [14.5868471 ],
       [14.14825896],
       [33.64440212],
       [16.4084144 ],
       [12.94802999],
       [25.33171106],
       [11.63823928],
       [27.55768009],
       [28.33885321],
       [25.99293289],
       [28.80600906],
       [22.58543728],
       [23.51563186],
       [22.23840881],
       [20.13970345],
       [23.43222912],
       [22.78918731],
       [13.51549257],
       [24.67705368],
       [24.11068014],
       [15.69289519],
       [25.75987427],
       [21.01064241],
       [ 7.42605431],
       [12.63471686],
       [26.33892861],
       [18.16756925],
       [14.54645667],
       [13.15787271],
       [22.62485437],
       [17.01828486],
       [17.45145759],
       [20.4720305 ],
       [12.13773142],
       [23.32685326],
       [23.40826397],
       [ 5.04735937],
       [21.15276665],
       [16.46504877],
       [ 7.50787856],
       [15.5445821 ],
       [24.93974939],
       [22.43667997],
       [22.07933276],
       [30.59042387],
       [20.55883827],
       [28.19043108],
       [36.18656141],
       [24.92716804],
       [31.66669736],
       [12.08072008],
       [15.06804068],
       [38.20623492],
       [24.68543168],
       [16.530597  ],
       [15.24205981],
       [18.36988557],
       [24.16834319],
       [ 5.26941358],
       [19.96053119],
       [24.28930591],
       [30.55445095],
       [16.45976734],
       [24.44275727],
       [ 8.24755919],
       [27.88393212],
       [15.9377853 ],
       [20.28862336],
       [21.68204593],
       [32.15659333],
       [16.03983526],
       [17.83666892],
       [35.62051148],
       [16.92643093],
       [22.16221411],
       [13.98972198],
       [31.52283649],
       [20.8239347 ],
       [14.06300154],
       [21.9643857 ],
       [18.14487753],
       [37.46625305],
       [31.31760465],
       [35.90223301],
       [28.35223628],
       [29.61336173],
       [20.82290084],
       [23.30490069],
       [20.48198523],
       [20.10540316],
       [16.0618067 ],
       [ 3.65815213],
       [34.55399995],
       [38.42974507],
       [30.23897244],
       [27.2845092 ],
       [13.57406946],
       [28.61199852],
       [14.65804725],
       [21.94042739],
       [16.65003707],
       [22.78647716],
       [23.1014238 ],
       [25.69834064],
       [14.35887167],
       [27.99397055],
       [30.16058016],
       [19.41413407],
       [14.54749881],
       [18.37581854],
       [29.86695394],
       [20.10242798],
       [26.43325894],
       [23.44305368],
       [24.76773509],
       [13.411788  ],
       [17.47212103],
       [14.71882388],
       [26.79888222],
       [13.14995568],
       [19.64452424],
       [19.80102801],
       [21.92812578],
       [37.61785645],
       [17.22352034],
       [42.57247261],
       [15.73691264],
       [23.28850698],
       [21.40262459],
       [15.36384041],
       [19.25927194],
       [13.1651778 ],
       [40.98051612],
       [21.41647726],
       [12.78240525],
       [32.05427222],
       [24.01857792],
       [19.23144812],
       [32.44527725],
       [21.11972755],
       [27.06098178],
       [28.59424173],
       [19.49376505],
       [20.36339302],
       [18.54774558],
       [20.26363631],
       [28.47445075],
       [19.26403892],
       [21.43840117],
       [11.48606091],
       [ 5.57440037],
       [28.65846186],
       [19.54744776],
       [10.24451627],
       [31.05125043],
       [17.29343118],
       [26.00470601],
       [20.31295209],
       [40.38010324],
       [15.68863026],
       [22.18571695],
       [18.52059741],
       [17.07281298],
       [35.67428452],
       [18.73459201],
       [18.29860775],
       [11.02349236],
       [14.9820073 ],
       [19.85989632],
       [30.02136891],
       [15.10433504],
       [13.55213931],
       [20.52967108],
       [24.79377372],
       [41.41634514],
       [20.9808245 ],
       [35.7554867 ],
       [13.469343  ],
       [18.27108361],
       [23.21021187],
       [29.85743318],
       [30.23811065],
       [10.49696198],
       [17.26025638],
       [19.03482729],
       [18.14830571],
       [19.46660558],
       [24.26596131],
       [27.98844731],
       [23.83782552],
       [20.17418879],
       [12.64034905],
       [15.0086086 ],
       [16.72834384],
       [18.80453277],
       [21.05684791],
       [31.05374967],
       [32.20655093],
       [24.41482312],
       [23.63559153],
       [35.51069309],
       [27.95130519],
       [13.23633721],
       [18.23587424],
       [ 2.69932848],
       [27.46022079],
       [20.5873826 ],
       [29.37910625],
       [22.64645992],
       [17.84244096],
       [13.7266685 ],
       [33.45772949],
       [23.93305072],
       [21.00496545],
       [22.50699646],
       [ 6.86650856],
       [20.5839828 ],
       [18.95736811],
       [11.57922639],
       [24.91838689],
       [15.92775599],
       [26.49964947],
       [20.95237417],
       [16.48046294],
       [21.17045892],
       [11.01393365],
       [19.15756889],
       [25.04976548],
       [20.58736263],
       [32.79395111],
       [33.19224769],
       [17.13504078],
       [12.65493346],
       [14.6286865 ],
       [23.65831747],
       [20.34168161],
       [33.92667497],
       [20.21036014],
       [20.17580614],
       [16.64001592],
       [23.7919132 ],
       [25.48239093],
       [22.25889274],
       [23.60907598],
       [18.95249474],
       [20.99392836],
       [20.51516262]])

In [963]:
real_vs_prezis_df = pd.DataFrame({"y_real":y_train["medv"], "y_prezis":y_prezis.flatten()})
real_vs_prezis_df

     y_real   y_prezis
289    22.3  26.531183
73     22.8  24.345829
472    19.6  22.655810
177    23.2  25.179156
321    23.8  24.750603
..      ...        ...
64     25.0  22.258893
327    23.0  23.609076
338    18.5  18.952495
12     18.9  20.993928
352    24.1  20.515163

[404 rows x 2 columns]

In [964]:
real_vs_prezis_df["score"] = real_vs_prezis_df["y_real"] - real_vs_prezis_df["y_prezis"]
real_vs_prezis_df

     y_real   y_prezis     score
289    22.3  26.531183 -4.231183
73     22.8  24.345829 -1.545829
472    19.6  22.655810 -3.055810
177    23.2  25.179156 -1.979156
321    23.8  24.750603 -0.950603
..      ...        ...       ...
64     25.0  22.258893  2.741107
327    23.0  23.609076 -0.609076
338    18.5  18.952495 -0.452495
12     18.9  20.993928 -2.093928
352    24.1  20.515163  3.584837

[404 rows x 3 columns]

In [965]:
real_vs_prezis_df["score"] = (real_vs_prezis_df["y_real"] - real_vs_prezis_df["y_prezis"]) ** 2
real_vs_prezis_df

     y_real   y_prezis      score
289    22.3  26.531183  17.902907
73     22.8  24.345829   2.389588
472    19.6  22.655810   9.337975
177    23.2  25.179156   3.917058
321    23.8  24.750603   0.903646
..      ...        ...        ...
64     25.0  22.258893   7.513669
327    23.0  23.609076   0.370974
338    18.5  18.952495   0.204751
12     18.9  20.993928   4.384536
352    24.1  20.515163  12.851059

[404 rows x 3 columns]

In [966]:
real_vs_prezis_df["score"] = np.sqrt((real_vs_prezis_df["y_real"] - real_vs_prezis_df["y_prezis"]) ** 2)
real_vs_prezis_df

     y_real   y_prezis     score
289    22.3  26.531183  4.231183
73     22.8  24.345829  1.545829
472    19.6  22.655810  3.055810
177    23.2  25.179156  1.979156
321    23.8  24.750603  0.950603
..      ...        ...       ...
64     25.0  22.258893  2.741107
327    23.0  23.609076  0.609076
338    18.5  18.952495  0.452495
12     18.9  20.993928  2.093928
352    24.1  20.515163  3.584837

[404 rows x 3 columns]

In [967]:
real_vs_prezis_df["score"].sum()

np.float64(1243.2354205105667)

In [968]:
real_vs_prezis_df["score"].sum() / real_vs_prezis_df["score"].count()

np.float64(3.0773153973033827)

In [969]:
real_vs_prezis_df["score"].mean()

np.float64(3.0773153973033827)

In [970]:
real_vs_prezis_df["score"].mean() / 2

np.float64(1.5386576986516913)

In [971]:
from sklearn.metrics import r2_score

In [972]:
y_prezis = model.predict(x_train)
r2_score(y_train, y_prezis)

0.7513747062933072

In [973]:
model.score(x_train, y_train)

0.7513747062933072

In [974]:
x.iloc[100]

crim         0.14866
zn           0.00000
indus        8.56000
chas         0.00000
nox          0.52000
rm           6.72700
age         79.90000
dis          2.77780
rad          5.00000
tax        384.00000
ptratio     20.90000
black      394.76000
lstat        9.42000
Name: 101, dtype: float64

In [975]:
model.predict([x.iloc[100]])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[24.67738776]])