In [748]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

In [749]:
df = pd.read_csv("datasets/Boston_cu_headere.csv", index_col=0)
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [750]:
# pentru a lua o coloana cu 2 seturi de paranteze drepte -> DataFrame
y = df[ [ "medv"] ]
x = df.drop("medv", axis=1) # axis=0 orizontala si axis=1 este pe verticala

In [751]:
# x_scaled = StandardScaler().fit_transform(x)
# x_scaled

In [752]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)#, random_state=142)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((404, 13), (102, 13), (404, 1), (102, 1))

In [753]:
x_train

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
227,0.38214,0.0,6.20,0,0.504,8.040,86.5,3.2157,8,307,17.4,387.38,3.13
405,41.52920,0.0,18.10,0,0.693,5.531,85.4,1.6074,24,666,20.2,329.46,27.38
432,10.06230,0.0,18.10,0,0.584,6.833,94.3,2.0882,24,666,20.2,81.33,19.69
330,0.06724,0.0,3.24,0,0.460,6.333,17.2,5.2146,4,430,16.9,375.21,7.34
338,0.03041,0.0,5.19,0,0.515,5.895,59.6,5.6150,5,224,20.2,394.81,10.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,14.43830,0.0,18.10,0,0.597,6.852,100.0,1.4655,24,666,20.2,179.36,19.78
159,1.34284,0.0,19.58,0,0.605,6.066,100.0,1.7573,5,403,14.7,353.89,6.43
86,0.05735,0.0,4.49,0,0.449,6.630,56.1,4.4377,3,247,18.5,392.30,6.53
284,0.01501,90.0,1.21,1,0.401,7.923,24.8,5.8850,1,198,13.6,395.52,3.16
132,1.19294,0.0,21.89,0,0.624,6.326,97.7,2.2710,4,437,21.2,396.90,12.26

In [754]:
from sklearn.pipeline import Pipeline

In [755]:
pipeline_steps = [
    ("scaler", StandardScaler() ), ( "model", LinearRegression())
]

In [756]:
linear_pipeline_model = Pipeline(steps=pipeline_steps)
linear_pipeline_model

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

In [757]:
linear_pipeline_model.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('model', LinearRegression())])

In [758]:
linear_pipeline_model.score(x_test, y_test)

0.738842997540191

In [759]:
knn_model = KNeighborsRegressor()
grid_model = GridSearchCV(estimator = knn_model, param_grid= {
    'n_neighbors':range(2, 11)
})

In [760]:
knn_pipeline_steps = [
    ("scaler", StandardScaler() ), ( "model", grid_model)
]

In [761]:
knn_pipeline_model = Pipeline(steps=knn_pipeline_steps)
knn_pipeline_model

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 GridSearchCV(estimator=KNeighborsRegressor(),
                              param_grid={'n_neighbors': range(2, 11)}))])

In [762]:
knn_pipeline_model.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('model',
                 GridSearchCV(estimator=KNeighborsRegressor(),
                              param_grid={'n_neighbors': range(2, 11)}))])

In [763]:
knn_pipeline_model.score(x_test, y_test)

0.8440490527042621

In [764]:
from  sklearn.datasets import load_boston

ImportError:
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>

In [765]:
from  sklearn.datasets import load_bucharest

ImportError: cannot import name 'load_bucharest' from 'sklearn.datasets' (/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/datasets/__init__.py)